server:
    port: 8080
    tomcat:
        connection-timeout: 5s
        threads:
            max: 200

demo:
    greeting: "Hello, folks!"

---

spring:
    config:
        activate:
            on-cloud-platform: kubernetes

demo:
    greeting: "Hello, Kubernetes!"
